import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { AuthProvider } from "@/context/AuthProvider";
import SidebarMenu from "@/components/SidebarMenu";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <div className="flex">
        <SidebarMenu />

        <div className="flex flex-1 flex-col h-screen overflow-auto">
          <NextTopLoader showSpinner={false} />
          {children}
        </div>
      </div>
    </AuthProvider>
  );
}

