import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthProvider";
import SidebarMenu from "@/components/SidebarMenu";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={`${inter.className} antialiased`}>
          <Toaster position="top-right" richColors />

          <div className="flex">
            <div className="flex flex-1 flex-col h-screen overflow-auto">
              {children}
            </div>
          </div>
          <div id="portal-root" />
        </body>
      </AuthProvider>
    </html>
  );
}

